services:
  zeus-site:
    build: .
    container_name: zeus-site
    restart: always
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: .env.production
        required: false
    environment:
      - NODE_ENV=production
