/* Generated by Payload — do not edit manually.
   Run `npm run generate:types` after starting with a live DATABASE_URI to regenerate. */

export type User = {
  id: number;
  name?: string | null;
  role?: "admin" | "agent" | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
};

export type Post = {
  id: number;
  title: string;
  slug: string;
  status: "draft" | "published";
  publishedAt?: string | null;
  excerpt?: string | null;
  tags?: { tag?: string | null; id?: string | null }[] | null;
  featureImage?: number | Media | null;
  content?: Record<string, unknown> | null;
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
};

export type Page = {
  id: number;
  title: string;
  slug: string;
  status: "draft" | "published";
  excerpt?: string | null;
  content?: Record<string, unknown> | null;
  updatedAt: string;
  createdAt: string;
};

export type Media = {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
};

export type Config = {
  auth: {
    users: { token: string };
  };
  collections: {
    users: User;
    posts: Post;
    pages: Page;
    media: Media;
  };
  globals: Record<string, never>;
};
